// Content Brain MAX — zero-cost, industry-aware strategy engine.
export const CONTENT_ARCHITECTURES=[{id:'demo',name:'Demonstration',stages:['Attract','Trust','Convert'],metric:'watch time'},{id:'proof-first',name:'Proof First',stages:['Trust','Convert'],metric:'qualified replies'},{id:'diagnosis',name:'Expert Diagnosis',stages:['Trust'],metric:'profile visits'},{id:'objection-reversal',name:'Objection Reversal',stages:['Trust','Convert'],metric:'DMs / enquiries'},{id:'direct-response',name:'Direct Response',stages:['Convert'],metric:'leads'}];
export const PLATFORM_RULES={Instagram:{format:'Reel',seconds:'20–35 sec'},TikTok:{format:'Native short video',seconds:'18–30 sec'},YouTube:{format:'Short',seconds:'25–45 sec'},Facebook:{format:'Native video / post',seconds:'25–50 sec'},LinkedIn:{format:'Text / native video',seconds:'35–60 sec'}};
const KNOWLEDGE={
'Restaurant / Food':{aud:'people deciding where to eat or what to order',search:'finding a meal worth ordering',details:['freshness, texture and consistency','how each order is prepared','portion and value','speed and service'],hooks:['Want to know if a meal is worth ordering? Look at this before the first bite.','This is the detail that turns an ordinary menu item into the one customers come back for.','A menu can promise anything. The kitchen has to prove it.'],lines:['Start with the finished plate, then cut straight to the preparation. Point out one thing a customer can actually judge — freshness, texture, portion or how the order is finished.','Show a real order from ingredient to hand-off. Explain one choice the kitchen makes that changes what the customer tastes or experiences.','Put the food close to camera and make the proof visible. Avoid saying “quality”; describe the crispness, steam, colour, portion, grind, pour or preparation instead.'],ctas:['Save this for the next time you are deciding what to order.','Which matters more to you when choosing a place to eat: taste, portion, speed or atmosphere?','If this looks like your kind of meal, send it to the person you would share it with.']},
Photography:{aud:'people who want to look natural and confident in photos',search:'looking natural in photos',details:['light on the face','direction instead of stiff posing','expression and body position','the final image'],hooks:['Most people who say they are “not photogenic” are reacting to this mistake.','Good posing should not look like posing. Here is the difference.','Before you blame the camera, look at what the light is doing to the face.'],lines:['Show the finished portrait first, then reveal the direction that created it. Make the lesson about what the subject can do, not camera jargon.','Demonstrate the stiff version for one second, then the natural version. Explain the tiny change in hands, shoulders, chin or movement.','Put the light on the face before talking. Show how moving a person a small distance changes the photograph.'],ctas:['Save this before your next photo session.','Which part of being photographed makes you most uncomfortable?','Send this to someone who always says they are not photogenic.']},
'Real Estate':{aud:'buyers and sellers making a high-stakes property decision',search:'choosing a property wisely',details:['layout and usable space','condition beyond the cosmetics','location and daily lifestyle','price versus comparable value'],hooks:['Before you fall in love with a property, check this.','The prettiest feature in a home is rarely the one that protects your money.','Sellers often spend money fixing the wrong thing before listing.'],lines:['Open on the attractive feature, then deliberately move to the practical detail buyers should inspect. Explain why it matters to daily life or resale value.','Walk the space as a buyer would use it. Show one detail photographs can hide and give a question to ask at the viewing.','Compare cosmetic appeal with a practical consideration such as layout, condition or location. Give viewers a decision rule they can remember.'],ctas:['Save this for your next property viewing.','What is the one thing you refuse to compromise on in a home?','Send this to someone currently house hunting.']},
'Coach / Consultant':{aud:'people trying to solve a specific problem without wasting time',search:'solving the right business problem',details:['diagnosis before tactics','the highest-leverage priority','a repeatable framework','how progress is measured'],hooks:['Before you add another tactic, diagnose this first.','If you keep fixing the symptom, this problem keeps coming back.','The fastest progress often comes from removing the wrong priority.'],lines:['Name one symptom clients notice, then show the diagnostic question you use before recommending a tactic.','Write the framework on screen and apply it to one realistic example. The viewer should be able to use it immediately.','Show what you would stop, start or measure first. Keep the lesson to one decision rather than a list of generic tips.'],ctas:['Save this and use the question before choosing your next tactic.','What is the problem you keep trying to solve without getting traction?','Send this to someone who is doing more but not getting a better result.']},
'Beauty / Salon':{aud:'clients choosing a treatment and wanting a result that suits them',search:'choosing the right beauty treatment',details:['consultation and suitability','professional technique','aftercare','the finished result'],hooks:['The best treatment is not automatically the most expensive one.','A great result starts before the treatment begins — here.','Before choosing this treatment, check whether your goal actually matches it.'],lines:['Show the finished result, then explain the consultation decision that made the treatment suitable for that client.','Film one technique detail and explain what it changes. Keep claims realistic and show the result rather than promising perfection.','Give one aftercare instruction and explain what can happen when it is ignored.'],ctas:['Save this before booking your next treatment.','What result are you actually trying to achieve?','Send this to someone comparing treatment options.']},
'Fitness / Wellness':{aud:'people who want sustainable progress without unnecessary complexity',search:'building a sustainable fitness routine',details:['safe form','appropriate progression','recovery','consistency'],hooks:['If this exercise never feels right, check this before adding more weight.','Progress is not always “do more”. Sometimes it is this correction.','The beginner mistake is copying the advanced version too soon.'],lines:['Show the common form error briefly, then demonstrate the safer version and point to the one body position that changed.','Demonstrate the beginner and progressed versions side by side. Explain who should use each one.','Show a simple routine or recovery habit and connect it to consistency rather than promising a dramatic body result.'],ctas:['Save this for your next session.','Which exercise would you like broken down next?','Send this to a training partner who rushes the progression.']},
'Retail / Ecommerce':{aud:'shoppers comparing products and trying to choose the right one',search:'choosing the right product',details:['real use case','material and construction','fit for the customer','durability and value'],hooks:['Do not choose between these two products by price alone.','This tiny product detail tells you who it is actually made for.','Before you add this to cart, ask yourself this one question.'],lines:['Use the product in a real situation. Show the feature doing its job instead of reading the feature list.','Put two options side by side and explain the customer or use case each suits. Do not manufacture a winner.','Zoom into one material, construction or fit detail and translate it into what the buyer will notice in everyday use.'],ctas:['Save this before choosing between the two.','Which feature matters most to you in everyday use?','Send this to someone comparing these options.']},
'Education / Training':{aud:'learners who want to understand and apply a skill',search:'learning a skill properly',details:['a concrete example','deliberate practice','useful feedback','real application'],hooks:['If you understand the theory but still cannot do it, this is probably why.','Here is the mistake that makes this skill harder than it needs to be.','You can test whether you understand this in 30 seconds.'],lines:['Start with a quick test or example, then teach the one idea needed to solve it.','Show the wrong attempt and the improved attempt. Explain exactly what changed between them.','Give viewers a 30-second practice exercise they can try immediately after watching.'],ctas:['Try this once, then save it for practice.','What part of this skill still feels confusing?','Send this to someone learning the same skill.']},
'Professional Service':{aud:'clients comparing providers and trying to reduce risk',search:'choosing a professional service',details:['a clear process','scope and expectations','evidence of competence','communication and delivery'],hooks:['Before hiring a professional, ask this before you ask the price.','A polished proposal does not prove the work will be good. This does.','The expensive mistake is choosing a provider before clarifying this.'],lines:['Show a real deliverable or process step and explain what a client should look for when comparing providers.','Take one vague promise providers make and replace it with evidence a customer can actually verify.','Show how scope, communication or delivery is handled before the work starts. Explain why that reduces risk later.'],ctas:['Save this before comparing providers.','What would make you feel confident before hiring someone?','Send this to someone about to request quotes.']},
'Creator / Personal Brand':{aud:'people following for useful ideas, perspective and credible experience',search:'improving your content process',details:['a specific lesson','the real process','evidence and examples','a useful point of view'],hooks:['I stopped doing this because it made the work look better but perform worse.','Here is the part of my process I wish I had learned earlier.','This advice sounds smart until you try to use it in real life.'],lines:['Show the old approach and the current approach. Explain the result that made you change your mind.','Film the real process in motion and narrate one decision that viewers normally never see.','Take one popular piece of advice and test it against a concrete example from your work.'],ctas:['Save this if you are testing your own process.','What advice have you stopped following?','Send this to a creator who would have an opinion on it.']}}

const PUBLISH_READY_COPY={
'Restaurant / Food':[
{script:'Look at that finish. The outside has the texture you want, the centre stays tender, and every order is prepared this way—not dressed up just for the camera. If you like food that tastes as good as it looks, this is the plate to try.',caption:'A menu can make a promise. The plate has to keep it. We focus on the details you can see and taste: careful preparation, satisfying texture and a finish worth coming back for.'},
{script:'This is what happens between ordering and the first bite. We prepare each part with purpose, finish it fresh, and check the details before it leaves the kitchen. That process is why the last order of the day should feel as good as the first.',caption:'Good food is not an accident. Here is a real look at the preparation behind every order—from the first ingredient to the final hand-off.'},
{script:'You do not need us to call it quality. Look at the colour, the texture, the portion and the way it is finished. Those are the details that tell you whether a meal is worth ordering before you ever take the first bite.',caption:'Skip the vague promises. Judge this one by the visible details: freshness, texture, portion and preparation.'}],
Photography:[
{script:'If you think you are not photogenic, the problem may be the direction—not you. A small change in your shoulders, hands and chin creates a pose that feels natural instead of forced. My job is to guide those details so you can stop wondering what to do.',caption:'“I am not photogenic” usually means “I have never been directed in a way that feels natural.” The right guidance changes everything.'},
{script:'Here is the stiff version, and here is the natural version. The difference is movement: relax the hands, shift the weight and let the expression happen between poses. You do not need to perform for the camera; you need direction you can trust.',caption:'Natural photographs are rarely accidental. Tiny changes in movement, posture and expression create the difference.'},
{script:'Watch what happens when we move just a step toward better light. The face looks brighter, the eyes come alive and the image feels more flattering before I change a single camera setting. Good photography starts with seeing the light.',caption:'Before blaming the camera, check the light. One small move can completely change how a portrait feels.'}],
'Real Estate':[
{script:'This room photographs beautifully, but before you fall in love, check how the layout works on an ordinary day. Where does the furniture go? Is there a clear walking path? The best home is not just impressive for a viewing—it supports the way you actually live.',caption:'A beautiful feature catches your eye. A practical layout protects your decision. Check both before you fall in love with a property.'},
{script:'Do not judge this home from the listing photos alone. Walk the route you would use every day, open the storage, listen to the street and check the details the camera cannot show. A viewing should answer how living here will feel.',caption:'Property photos start the conversation; a careful walk-through reveals the decision. Save these checks for your next viewing.'},
{script:'Fresh paint can make a home feel new, but it does not tell you about layout, condition or long-term value. Compare the cosmetic finish with the things that are expensive or impossible to change. That is how you buy with your head as well as your heart.',caption:'Cosmetic appeal is easy to notice. Layout, condition and location are harder to change—and often matter more.'}],
'Coach / Consultant':[
{script:'Before you add another tactic, answer this: what is the actual bottleneck? If leads are coming in but sales are not, more traffic will not solve the problem. Diagnose the stage where progress stops, then fix that stage first.',caption:'More tactics do not fix the wrong problem. Find the bottleneck, choose one measure and solve the stage where progress stops.'},
{script:'Use this simple test: write down the result you want, the behaviour that creates it and the obstacle preventing that behaviour. If your next action does not address that obstacle, it is probably just more activity—not progress.',caption:'A useful plan connects the result, the required behaviour and the real obstacle. Try this three-line diagnosis before choosing your next tactic.'},
{script:'Here is what I would stop first: work that is urgent but does not change the result. Then I would choose one priority and one number that proves it is working. Clear measurement makes it much easier to say no to distractions.',caption:'Stop, start, measure: remove low-value activity, choose one priority and track the signal that proves it is working.'}],
'Beauty / Salon':[
{script:'The best treatment is not automatically the most expensive one. It is the one that matches your goal, starting point and aftercare routine. A proper consultation lets us choose for your result—not simply sell the biggest service.',caption:'The right treatment starts with the right consultation. Your goal, starting point and routine should shape the recommendation.'},
{script:'This small technique detail changes the whole finish. We control the placement and pressure here so the result looks balanced, comfortable and suited to the client. Professional work is often about the details that are easy to miss.',caption:'Great results live in the details: careful placement, controlled technique and a finish designed for the individual client.'},
{script:'Your appointment creates the result; your aftercare helps protect it. Follow the first-day guidance, use the recommended products and do not rush the recovery process. A few simple choices at home can make the finish last much better.',caption:'Aftercare is part of the treatment. Save these first-day rules so you can protect your result at home.'}],
'Fitness / Wellness':[
{script:'If this movement never feels right, pause before adding more weight. Keep the joint stacked here, control the range and make the target muscle do the work. Better position usually creates more progress than forcing another repetition.',caption:'Before adding weight, improve the position. Controlled range and correct alignment make every repetition more useful.'},
{script:'Start with the version you can control. When you can repeat it with steady form and no compensation, progress to this variation. The advanced option is not better if your body is not ready to own it.',caption:'Progression should be earned through control. Use the version that lets you move well, then build from there.'},
{script:'A routine only works if you can repeat it. Choose a realistic session, protect recovery and leave enough energy to return tomorrow. Consistency may look less dramatic, but it is what turns one good week into lasting progress.',caption:'Sustainable progress is repeatable: realistic training, enough recovery and a routine you can continue next week.'}],
'Retail / Ecommerce':[
{script:'Here is what this feature feels like in real life. It keeps the item secure, stays comfortable during normal use and removes the small frustration cheaper versions often create. That is more useful than simply reading a specification list.',caption:'Features matter when they improve everyday use. Here is the detail doing the job it was designed to do.'},
{script:'Choose this option if you want simplicity and everyday value. Choose this one if you need extra capacity and use it often. Neither is universally better—the right choice depends on how you will actually use it.',caption:'Two good options, two different customers. Compare the real use case before comparing the price tag.'},
{script:'Look closely at this join and the material around it. This is where daily wear usually appears first, so the construction here tells you more about long-term value than the packaging ever could.',caption:'The smallest construction detail can reveal how a product will handle everyday use. This is the area worth checking.'}],
'Education / Training':[
{script:'Quick test: can you explain this idea with one real example? If not, you may recognise the words without understanding how to use them. Start with the example, identify the rule behind it, then try a new example without looking.',caption:'Recognition is not the same as understanding. Test the skill with one new example you have to solve yourself.'},
{script:'Here is the common mistake: trying to complete every step at once. Break the skill into one decision, practise that decision slowly, then add the next step. Accuracy first makes speed much easier later.',caption:'Make a difficult skill easier by isolating one decision. Practise it accurately, then rebuild the full process.'},
{script:'Try this for thirty seconds: cover the answer, solve one example aloud and explain why each step is necessary. If you get stuck, you have found the exact part to practise next.',caption:'A 30-second practice test: solve one example aloud and explain every step. The hesitation shows you what to review.'}],
'Professional Service':[
{script:'Before hiring a professional, ask what the process looks like after you say yes. You should know the scope, the next step, who communicates with you and what a finished deliverable includes. Clarity before the work starts prevents expensive surprises later.',caption:'Do not compare providers on price alone. A clear scope, communication plan and deliverable reduce risk before the work begins.'},
{script:'“Great service” is a promise. This is the evidence: a defined process, visible checkpoints and a deliverable you can evaluate. Ask a provider to show how the work moves from brief to completion—not just tell you it will be excellent.',caption:'Replace vague promises with verifiable evidence. Ask to see the process, checkpoints and finished deliverable.'},
{script:'This is how we prevent small misunderstandings becoming large problems. We agree the scope, confirm responsibilities and set communication checkpoints before delivery begins. When expectations are visible, the work moves faster and surprises disappear.',caption:'Strong delivery starts before the work. Clear scope, ownership and communication checkpoints keep everyone aligned.'}],
'Creator / Personal Brand':[
{script:'I stopped polishing every post until it looked perfect because the work was becoming less useful and less human. Now I lead with one clear idea, show the real example and publish when the lesson is useful. Clarity has done more for my content than perfection ever did.',caption:'I traded perfect-looking content for clearer, more useful ideas. The result: a process I can sustain and work people can actually use.'},
{script:'This is the part of the process people rarely see. Before I create the final piece, I remove anything that does not support the main idea. The result looks simple because the difficult decisions happened earlier.',caption:'Simple work often comes from hard editing. Here is the unseen decision that makes the finished result clearer.'},
{script:'“Post more” sounds useful until volume starts lowering the quality of every idea. I would rather publish one specific example with a real point of view than five vague posts made to satisfy a schedule.',caption:'More content is not automatically better content. Specific examples and a clear point of view beat volume without purpose.'}]
};
function publishCopy(p,index){const set=PUBLISH_READY_COPY[p.industry]||PUBLISH_READY_COPY['Professional Service'];return set[index%set.length]}

const BAD_INPUTS=/^(everyone|anyone|people|all|none|n\/a)$/i;
export function safeText(v,f=''){const x=(v||'').trim();if(!x||BAD_INPUTS.test(x))return f;const low=x.toLowerCase();if(low==='quality coffee and tasty meals'||low==='quality coffee & tasty meals')return 'freshness, preparation and consistency';if(low==='best coffee and great food'||low==='best coffee & great food')return 'a meal customers genuinely want to come back for';return x}
function k(p){return KNOWLEDGE[p.industry]||KNOWLEDGE['Professional Service']}
export function chooseArchitecture(i,stage){if(stage==='Attract')return CONTENT_ARCHITECTURES[0];if(stage==='Trust')return [CONTENT_ARCHITECTURES[1],CONTENT_ARCHITECTURES[2],CONTENT_ARCHITECTURES[0],CONTENT_ARCHITECTURES[3]][i%4];return [CONTENT_ARCHITECTURES[1],CONTENT_ARCHITECTURES[3],CONTENT_ARCHITECTURES[4]][i%3]}
function normalise(s){return (s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
export function buildCreativeBrief({index=0,stage='Attract',p,topic,proof}){const x=k(p),architecture=chooseArchitecture(index,stage),platform=PLATFORM_RULES[p.platform]||PLATFORM_RULES.Instagram,audience=safeText(p.audience,x.aud),offer=safeText(p.offer,p.industry.toLowerCase()),objection=safeText(p.objection,'not knowing which option to trust'),realProof=safeText(p.proof,proof);let search=safeText(p.topic,topic||x.search),ns=normalise(search),nb=normalise(p.business);if(!search||ns===nb||(nb&&ns.includes(nb))||(p.industry==='Restaurant / Food'&&/come\s*back\s*coffee/i.test(search)))search=x.search;const copy=publishCopy(p,index);return{architecture,platform,audience,offer,hooks:x.hooks,search,proof:realProof,direction:x.lines[index%x.lines.length],script:copy.script,caption:copy.caption,cta:x.ctas[index%x.ctas.length],detail:x.details[index%x.details.length],objective:stage==='Attract'?'Stop the right customer with a recognisable problem or desire':stage==='Trust'?'Replace uncertainty with specific, visible evidence':'Turn earned trust into one clear commercial next step'};}
export function qualityCheck(t){const bad=['a specific customer','better decisions','loudest claim','the obvious way','generic tips','quality coffee and tasty meals','best coffee and great food','come back coffee'];const hits=bad.filter(x=>(t||'').toLowerCase().includes(x));return{pass:!hits.length,score:Math.max(0,100-hits.length*20),problems:hits};}
