// Content Brain MAX — zero-cost, industry-aware strategy engine.
export const CONTENT_ARCHITECTURES=[
{id:'mistake-fix',name:'Mistake → Fix',stages:['Attract','Trust'],metric:'saves'},{id:'proof-first',name:'Proof First',stages:['Trust','Convert'],metric:'qualified replies'},{id:'micro-story',name:'Micro Story',stages:['Attract','Trust'],metric:'completion rate'},{id:'comparison',name:'Comparison',stages:['Trust','Convert'],metric:'shares'},{id:'diagnosis',name:'Expert Diagnosis',stages:['Trust'],metric:'profile visits'},{id:'demo',name:'Demonstration',stages:['Attract','Trust','Convert'],metric:'watch time'},{id:'objection-reversal',name:'Objection Reversal',stages:['Trust','Convert'],metric:'DMs / enquiries'},{id:'direct-response',name:'Direct Response',stages:['Convert'],metric:'leads'}];
export const PLATFORM_RULES={Instagram:{format:'Reel',seconds:'20–35 sec'},TikTok:{format:'Native short video',seconds:'18–30 sec'},YouTube:{format:'Short',seconds:'25–45 sec'},Facebook:{format:'Native video / post',seconds:'25–50 sec'},LinkedIn:{format:'Text / native video',seconds:'35–60 sec'}};
const KNOWLEDGE={
'Restaurant / Food':{aud:'people deciding where to eat or what to order',search:'best local food',stakes:'taste, consistency and whether the experience feels worth the money',details:['texture','freshness','portion','preparation','service'],hooks:['If you only judge a restaurant by the menu, you miss the part that matters most.','This is the detail I check before calling a dish a signature dish.','Want to know if a meal is worth ordering? Look at this before the first bite.'],rules:['Show the finished dish before explaining it.','Use a real order, ingredient or preparation step as evidence.','Describe what the customer can see, taste or experience; never hide behind “quality”.']},
Photography:{aud:'people who want to look natural and confident in photos',search:'how to look natural in photos',stakes:'feeling comfortable, looking like themselves and receiving images they are proud to use',details:['light','posing','expression','direction','final image'],hooks:['Most people who say they are “not photogenic” are reacting to this mistake.','Good posing should not look like posing. Here is the difference.','Before you blame the camera, look at what the light is doing to the face.'],rules:['Show the final photograph early.','Demonstrate the direction given to the subject.','Use before/after evidence without shaming the person.']},
'Real Estate':{aud:'buyers and sellers trying to make a high-stakes property decision',search:'property buying and selling tips',stakes:'price, hidden risk, lifestyle fit and avoiding an expensive mistake',details:['layout','condition','location','price','buyer demand'],hooks:['The prettiest feature in a home is rarely the one that protects your money.','Before you fall in love with a property, check this.','Sellers often spend money fixing the wrong thing before listing.'],rules:['Show the actual feature being discussed.','Separate emotional appeal from decision evidence.','Give a practical question buyers or sellers can use immediately.']},
'Coach / Consultant':{aud:'people trying to solve a specific business or personal problem',search:'how to solve the problem',stakes:'clarity, progress and avoiding wasted time or money',details:['diagnosis','priority','framework','execution','measurement'],hooks:['If you keep fixing the symptom, this problem keeps coming back.','Before you add another tactic, diagnose this first.','The fastest progress often comes from removing the wrong priority.'],rules:['Teach one decision, not five vague tips.','Show the framework or diagnostic question.','Connect advice to a measurable outcome.']},
'Beauty / Salon':{aud:'clients choosing a treatment and wanting a result that suits them',search:'how to choose the right beauty treatment',stakes:'suitability, realistic results, maintenance and trust',details:['consultation','technique','product','aftercare','finished result'],hooks:['The best treatment is not automatically the most expensive one.','Before choosing this treatment, check whether your goal actually matches it.','A great result starts before the treatment begins — here.'],rules:['Lead with a real finished result when appropriate.','Explain suitability and aftercare honestly.','Never imply guaranteed or unrealistic results.']},
'Fitness / Wellness':{aud:'people who want sustainable progress without unnecessary complexity',search:'fitness tips for beginners',stakes:'consistency, safe technique and realistic progress',details:['form','progression','recovery','consistency','habit'],hooks:['If this exercise never feels right, check this before adding more weight.','Progress is not always “do more”. Sometimes it is this correction.','The beginner mistake is copying the advanced version too soon.'],rules:['Demonstrate safe form and a modification.','Avoid guaranteed body or health outcomes.','Give a simple progression viewers can understand.']},
'Retail / Ecommerce':{aud:'shoppers comparing products and trying to choose the right one',search:'how to choose the right product',stakes:'fit, usefulness, durability and value',details:['use case','material','fit','feature','durability'],hooks:['Do not choose between these two products by price alone.','This tiny product detail tells you who it is actually made for.','Before you add this to cart, ask yourself this one question.'],rules:['Show the product in use.','Compare meaningful differences, not invented superiority.','Translate features into real use cases.']},
'Education / Training':{aud:'learners who want to understand and apply a skill',search:'how to learn the skill',stakes:'understanding, confidence and practical improvement',details:['example','practice','feedback','mistake','application'],hooks:['If you understand the theory but still cannot do it, this is probably why.','Here is the mistake that makes this skill harder than it needs to be.','You can test whether you understand this in 30 seconds.'],rules:['Teach with an example, not a definition alone.','Show wrong versus better where useful.','End with something the learner can practise.']},
'Professional Service':{aud:'clients comparing providers and trying to reduce risk',search:'how to choose a professional service',stakes:'trust, competence, process clarity and avoiding costly mistakes',details:['process','scope','evidence','communication','result'],hooks:['Before hiring a professional, ask this before you ask the price.','A polished proposal does not prove the work will be good. This does.','The expensive mistake is choosing a provider before clarifying this.'],rules:['Show a process, deliverable or client-safe result.','Explain what good evidence looks like.','Never use expertise as a substitute for proof.']},
'Creator / Personal Brand':{aud:'people following for useful ideas, perspective and credible experience',search:'content creator tips',stakes:'relevance, trust and a reason to keep following',details:['lesson','process','example','opinion','result'],hooks:['I stopped doing this because it made the work look better but perform worse.','Here is the part of my process I wish I had learned earlier.','This advice sounds smart until you try to use it in real life.'],rules:['Use a specific lived example.','Have a point of view without manufacturing controversy.','Give the audience a useful takeaway, not autobiography alone.']}}
export function safeText(v,f=''){const x=(v||'').trim();return !x||/^(everyone|anyone|people|all|none|n\/a)$/i.test(x)?f:x}
export function chooseArchitecture(i,stage){const a=CONTENT_ARCHITECTURES.filter(x=>x.stages.includes(stage));return a[i%a.length]}
function k(p){return KNOWLEDGE[p.industry]||KNOWLEDGE['Professional Service']}
export function buildCreativeBrief({index=0,stage='Attract',p,topic,proof}){const x=k(p),architecture=chooseArchitecture(index,stage),platform=PLATFORM_RULES[p.platform]||PLATFORM_RULES.Instagram,audience=safeText(p.audience,x.aud),offer=safeText(p.offer,p.industry.toLowerCase()),promise=safeText(p.promise,'a result the customer can actually judge'),objection=safeText(p.objection,'not knowing which option to trust'),differentiator=safeText(p.differentiator,x.details[index%x.details.length]),realProof=safeText(p.proof,proof),hook=x.hooks[index%x.hooks.length],search=safeText(p.topic,topic||x.search);return{architecture,platform,audience,offer,promise,objection,differentiator,proof:realProof,hook,hooks:x.hooks,search,stakes:x.stakes,rules:x.rules,details:x.details,objective:stage==='Attract'?'Stop the right customer with a problem they recognise':stage==='Trust'?'Replace uncertainty with specific, visible evidence':'Turn earned trust into one clear next step'};}
export function qualityCheck(t){const bad=['a specific customer','better decisions','loudest claim','the obvious way','generic tips','quality coffee and tasty meals'];const hits=bad.filter(x=>(t||'').toLowerCase().includes(x));return{pass:!hits.length,score:Math.max(0,100-hits.length*20),problems:hits};}
